# Generated by Django 5.1.2 on 2024-11-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participants_data',
        ),
    ]
