# Generated by Django 5.1.2 on 2024-11-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_remove_event_date_event_end_time_event_participants_and_more'),
        ('volunteer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='registered_participants', to='event_management.event'),
        ),
    ]
