# Generated by Django 5.1.2 on 2024-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_remove_event_participants_and_more'),
        ('volunteer_management', '0002_alter_participant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='event_management_event', to='event_management.event'),
        ),
    ]
