# Generated by Django 5.1.2 on 2024-11-22 09:38

import django.db.models.deletion
import volunteer_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_remove_event_participants_and_more'),
        ('volunteer_management', '0003_remove_participant_events_participant_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=volunteer_management.models.get_default_event, on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
    ]
