# Generated by Django 5.1.2 on 2024-11-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organizer', 'Organizer')], default='', max_length=20),
        ),
    ]
