# Generated by Django 5.1.2 on 2024-11-21 13:57

import django.db.models.deletion
import django.utils.timezone
import event_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_alter_eventparticipation_participant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(default=event_management.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='eventparticipations_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventparticipations_as_participant_unique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('participant', 'event')},
        ),
    ]
