# Generated by Django 5.1.2 on 2024-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_remove_event_date_event_end_time_event_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
